version: "3.8"

services:
  gu2-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gu2-frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
