version: "3.8"

services:
  gu2-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gu2-frontend
    ports:
      - "80:80" # 将容器内的80端口映射到宿主机的80端口
    environment:
      - NODE_ENV=production
    restart: unless-stopped
