/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as ProfileImport } from './routes/profile'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as TrainingManagementIndexImport } from './routes/training-management/index'
import { Route as TournamentManagementIndexImport } from './routes/tournament-management/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as PlayerManageIndexImport } from './routes/player-manage/index'
import { Route as ConsentFormIndexImport } from './routes/consent-form/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrainingManagementIndexRoute = TrainingManagementIndexImport.update({
  id: '/training-management/',
  path: '/training-management/',
  getParentRoute: () => rootRoute,
} as any)

const TournamentManagementIndexRoute = TournamentManagementIndexImport.update({
  id: '/tournament-management/',
  path: '/tournament-management/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerManageIndexRoute = PlayerManageIndexImport.update({
  id: '/player-manage/',
  path: '/player-manage/',
  getParentRoute: () => rootRoute,
} as any)

const ConsentFormIndexRoute = ConsentFormIndexImport.update({
  id: '/consent-form/',
  path: '/consent-form/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/consent-form/': {
      id: '/consent-form/'
      path: '/consent-form'
      fullPath: '/consent-form'
      preLoaderRoute: typeof ConsentFormIndexImport
      parentRoute: typeof rootRoute
    }
    '/player-manage/': {
      id: '/player-manage/'
      path: '/player-manage'
      fullPath: '/player-manage'
      preLoaderRoute: typeof PlayerManageIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/tournament-management/': {
      id: '/tournament-management/'
      path: '/tournament-management'
      fullPath: '/tournament-management'
      preLoaderRoute: typeof TournamentManagementIndexImport
      parentRoute: typeof rootRoute
    }
    '/training-management/': {
      id: '/training-management/'
      path: '/training-management'
      fullPath: '/training-management'
      preLoaderRoute: typeof TrainingManagementIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/consent-form': typeof ConsentFormIndexRoute
  '/player-manage': typeof PlayerManageIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournament-management': typeof TournamentManagementIndexRoute
  '/training-management': typeof TrainingManagementIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/consent-form': typeof ConsentFormIndexRoute
  '/player-manage': typeof PlayerManageIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournament-management': typeof TournamentManagementIndexRoute
  '/training-management': typeof TrainingManagementIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/consent-form/': typeof ConsentFormIndexRoute
  '/player-manage/': typeof PlayerManageIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournament-management/': typeof TournamentManagementIndexRoute
  '/training-management/': typeof TrainingManagementIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/consent-form'
    | '/player-manage'
    | '/teams'
    | '/tournament-management'
    | '/training-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/consent-form'
    | '/player-manage'
    | '/teams'
    | '/tournament-management'
    | '/training-management'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/consent-form/'
    | '/player-manage/'
    | '/teams/'
    | '/tournament-management/'
    | '/training-management/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ConsentFormIndexRoute: typeof ConsentFormIndexRoute
  PlayerManageIndexRoute: typeof PlayerManageIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentManagementIndexRoute: typeof TournamentManagementIndexRoute
  TrainingManagementIndexRoute: typeof TrainingManagementIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ConsentFormIndexRoute: ConsentFormIndexRoute,
  PlayerManageIndexRoute: PlayerManageIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentManagementIndexRoute: TournamentManagementIndexRoute,
  TrainingManagementIndexRoute: TrainingManagementIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/profile",
        "/signin",
        "/signup",
        "/consent-form/",
        "/player-manage/",
        "/teams/",
        "/tournament-management/",
        "/training-management/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/consent-form/": {
      "filePath": "consent-form/index.tsx"
    },
    "/player-manage/": {
      "filePath": "player-manage/index.tsx"
    },
    "/teams/": {
      "filePath": "teams/index.tsx"
    },
    "/tournament-management/": {
      "filePath": "tournament-management/index.tsx"
    },
    "/training-management/": {
      "filePath": "training-management/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
